import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Aurora } from "@/components/fx"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Inceptrax Privacy Policy — how we collect, use, and protect your data.",
}

/** Section heading with a small brand accent bar. */
function LegalHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="flex items-center gap-3 text-xl font-semibold tracking-tight text-foreground">
      <span
        aria-hidden
        className="h-5 w-1 shrink-0 rounded-full bg-gradient-to-b from-brand-cyan via-brand to-brand-violet"
      />
      {children}
    </h2>
  )
}

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow">
        {/* ── Hero ─────────────────────────────────────────── */}
        <section className="relative pt-36 pb-10 md:pt-44 md:pb-12 overflow-hidden">
          <Aurora intensity="subtle" />
          <div className="container px-4 max-w-3xl mx-auto relative z-10">
            <p className="eyebrow mb-4">Legal</p>
            <h1 className="mb-3 text-gradient-subtle">
              Privacy <span className="accent-serif text-gradient">Policy</span>
            </h1>
            <p className="text-xs font-mono uppercase tracking-[0.14em] text-muted-foreground/80">
              Last updated: April 28, 2026
            </p>
          </div>
        </section>

        {/* ── Body ─────────────────────────────────────────── */}
        <section className="pb-24">
          <div className="container px-4 max-w-3xl mx-auto">
            <div className="divider-glow mb-10" />

            <div className="animate-fade-up space-y-12 text-foreground/75 leading-relaxed text-[15px] marker:text-brand/70">

              <section className="space-y-4">
                <LegalHeading>1. What Data We Collect</LegalHeading>
                <p>When you use Inceptrax, we collect the following information:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong className="text-foreground/90">Account Information:</strong> Name, email address, and hashed password when you create an account.</li>
                  <li><strong className="text-foreground/90">Startup Ideas &amp; Analysis Data:</strong> The ideas you submit, AI-generated analysis results, stage scores, and any notes or checklists you create.</li>
                  <li><strong className="text-foreground/90">Usage Data:</strong> Pages visited, features used, timestamps, browser type, and device information collected via analytics tools.</li>
                  <li><strong className="text-foreground/90">Communication Data:</strong> Messages sent through the platform&apos;s chat feature and contact form submissions.</li>
                  <li><strong className="text-foreground/90">AI-Generated Content:</strong> Reports, pitch decks, and business plans generated by our AI on your behalf.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>2. How We Use Your Data</LegalHeading>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong className="text-foreground/90">Service Delivery:</strong> To provide AI-powered idea validation, market research, competitor analysis, and report generation.</li>
                  <li><strong className="text-foreground/90">Product Improvement:</strong> To understand usage patterns and improve our AI models and user experience.</li>
                  <li><strong className="text-foreground/90">Analytics:</strong> Aggregated, anonymized usage data helps us make product decisions. We use PostHog for product analytics.</li>
                  <li><strong className="text-foreground/90">Communication:</strong> To send analysis completion notifications, account-related emails, and (with consent) product updates.</li>
                  <li><strong className="text-foreground/90">Security:</strong> To detect and prevent fraud, abuse, and unauthorized access.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>3. Data Storage &amp; Security</LegalHeading>
                <p>Your data is stored securely using industry-standard practices:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Passwords are hashed using bcrypt with a cost factor of 12. We never store plaintext passwords.</li>
                  <li>Authentication uses JWT tokens stored as httpOnly cookies, preventing XSS attacks.</li>
                  <li>All data is transmitted over HTTPS in production.</li>
                  <li>Database access is restricted and monitored.</li>
                  <li><strong className="text-foreground/90">We do not sell, rent, or trade your personal data to third parties.</strong></li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>4. Your Rights</LegalHeading>
                <p>You have the following rights regarding your data:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong className="text-foreground/90">Access:</strong> You can view all your data through your dashboard.</li>
                  <li><strong className="text-foreground/90">Deletion:</strong> You can request complete deletion of your account and all associated data by contacting us.</li>
                  <li><strong className="text-foreground/90">Export:</strong> You can export your analysis reports as PDF or PPT at any time.</li>
                  <li><strong className="text-foreground/90">Correction:</strong> You can update your profile information through your settings page.</li>
                  <li><strong className="text-foreground/90">Opt-out:</strong> You can opt out of non-essential analytics by contacting us.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>5. Cookies</LegalHeading>
                <p>We use the following cookies:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong className="text-foreground/90">Essential:</strong> <code className="text-xs font-mono text-brand-cyan bg-white/[0.06] border border-white/10 px-1.5 py-0.5 rounded">access_token</code> (httpOnly, authentication) — required for the service to function.</li>
                  <li><strong className="text-foreground/90">Functional:</strong> <code className="text-xs font-mono text-brand-cyan bg-white/[0.06] border border-white/10 px-1.5 py-0.5 rounded">auth_session</code> (session flag) — used for client-side navigation protection.</li>
                  <li><strong className="text-foreground/90">Analytics:</strong> PostHog analytics cookies — used to understand product usage (anonymized).</li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>6. Third-Party Services</LegalHeading>
                <p>We integrate with the following services that may process your data:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong className="text-foreground/90">Google Gemini / Groq / OpenRouter:</strong> AI model providers that process your idea descriptions to generate analysis. Data is sent securely via API.</li>
                  <li><strong className="text-foreground/90">Vercel Analytics:</strong> Anonymous page view analytics.</li>
                  <li><strong className="text-foreground/90">PostHog:</strong> Product analytics for usage patterns.</li>
                  <li><strong className="text-foreground/90">Resend:</strong> Transactional email delivery.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <LegalHeading>7. Contact Us</LegalHeading>
                <p>For any privacy-related concerns, data deletion requests, or questions about this policy, contact us at:</p>
                <p className="font-semibold text-brand-cyan">privacy@inceptrax.com</p>
              </section>

              <section className="space-y-4">
                <LegalHeading>8. Jurisdiction</LegalHeading>
                <p>This privacy policy is governed by and construed in accordance with applicable law. By using Inceptrax, you consent to the collection and use of your data as described in this policy.</p>
              </section>

            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
