import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Inceptrax Privacy Policy — how we collect, use, and protect your data.",
}

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow py-20">
        <div className="container px-4 max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: April 28, 2026</p>

          <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground/80 leading-relaxed text-[15px]">

            <section>
              <h2 className="text-xl font-bold text-foreground">1. What Data We Collect</h2>
              <p>When you use Inceptrax, we collect the following information:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Account Information:</strong> Name, email address, and hashed password when you create an account.</li>
                <li><strong>Startup Ideas & Analysis Data:</strong> The ideas you submit, AI-generated analysis results, stage scores, and any notes or checklists you create.</li>
                <li><strong>Usage Data:</strong> Pages visited, features used, timestamps, browser type, and device information collected via analytics tools.</li>
                <li><strong>Communication Data:</strong> Messages sent through the platform&apos;s chat feature and contact form submissions.</li>
                <li><strong>AI-Generated Content:</strong> Reports, pitch decks, and business plans generated by our AI on your behalf.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">2. How We Use Your Data</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Service Delivery:</strong> To provide AI-powered idea validation, market research, competitor analysis, and report generation.</li>
                <li><strong>Product Improvement:</strong> To understand usage patterns and improve our AI models and user experience.</li>
                <li><strong>Analytics:</strong> Aggregated, anonymized usage data helps us make product decisions. We use PostHog for product analytics.</li>
                <li><strong>Communication:</strong> To send analysis completion notifications, account-related emails, and (with consent) product updates.</li>
                <li><strong>Security:</strong> To detect and prevent fraud, abuse, and unauthorized access.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">3. Data Storage & Security</h2>
              <p>Your data is stored securely using industry-standard practices:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Passwords are hashed using bcrypt with a cost factor of 12. We never store plaintext passwords.</li>
                <li>Authentication uses JWT tokens stored as httpOnly cookies, preventing XSS attacks.</li>
                <li>All data is transmitted over HTTPS in production.</li>
                <li>Database access is restricted and monitored.</li>
                <li><strong>We do not sell, rent, or trade your personal data to third parties.</strong></li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">4. Your Rights</h2>
              <p>You have the following rights regarding your data:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Access:</strong> You can view all your data through your dashboard.</li>
                <li><strong>Deletion:</strong> You can request complete deletion of your account and all associated data by contacting us.</li>
                <li><strong>Export:</strong> You can export your analysis reports as PDF or PPT at any time.</li>
                <li><strong>Correction:</strong> You can update your profile information through your settings page.</li>
                <li><strong>Opt-out:</strong> You can opt out of non-essential analytics by contacting us.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">5. Cookies</h2>
              <p>We use the following cookies:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Essential:</strong> <code className="text-xs bg-muted px-1.5 py-0.5 rounded">access_token</code> (httpOnly, authentication) — required for the service to function.</li>
                <li><strong>Functional:</strong> <code className="text-xs bg-muted px-1.5 py-0.5 rounded">auth_session</code> (session flag) — used for client-side navigation protection.</li>
                <li><strong>Analytics:</strong> PostHog analytics cookies — used to understand product usage (anonymized).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">6. Third-Party Services</h2>
              <p>We integrate with the following services that may process your data:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Google Gemini / Groq / OpenRouter:</strong> AI model providers that process your idea descriptions to generate analysis. Data is sent securely via API.</li>
                <li><strong>Vercel Analytics:</strong> Anonymous page view analytics.</li>
                <li><strong>PostHog:</strong> Product analytics for usage patterns.</li>
                <li><strong>Resend:</strong> Transactional email delivery.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">7. Contact Us</h2>
              <p>For any privacy-related concerns, data deletion requests, or questions about this policy, contact us at:</p>
              <p className="font-semibold">privacy@inceptrax.com</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">8. Jurisdiction</h2>
              <p>This privacy policy is governed by and construed in accordance with applicable law. By using Inceptrax, you consent to the collection and use of your data as described in this policy.</p>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
